package com.erircs.dao;

import com.erircs.pojos.ReportQuestion;
import com.erircs.pojos.ReportQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(ReportQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(ReportQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(ReportQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(ReportQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<ReportQuestion> selectByExample(ReportQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    ReportQuestion selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ReportQuestion record, @Param("example") ReportQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") ReportQuestion record, @Param("example") ReportQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(ReportQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(ReportQuestion record);
}