package com.erircs.dao;

import com.erircs.pojos.StudentSubmit;
import com.erircs.pojos.StudentSubmitExample;
import com.erircs.pojos.StudentSubmitKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentSubmitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(StudentSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(StudentSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(StudentSubmitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(StudentSubmit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(StudentSubmit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<StudentSubmit> selectByExample(StudentSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    StudentSubmit selectByPrimaryKey(StudentSubmitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") StudentSubmit record, @Param("example") StudentSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") StudentSubmit record, @Param("example") StudentSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(StudentSubmit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(StudentSubmit record);
}