package com.erircs.dao;

import com.erircs.pojos.StudentClassExample;
import com.erircs.pojos.StudentClassKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(StudentClassKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(StudentClassKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(StudentClassKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<StudentClassKey> selectByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") StudentClassKey record, @Param("example") StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") StudentClassKey record, @Param("example") StudentClassExample example);
}