package com.erircs.dao;

import com.erircs.pojos.TeacherMark;
import com.erircs.pojos.TeacherMarkExample;
import com.erircs.pojos.TeacherMarkKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(TeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(TeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(TeacherMarkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(TeacherMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(TeacherMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<TeacherMark> selectByExample(TeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    TeacherMark selectByPrimaryKey(TeacherMarkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TeacherMark record, @Param("example") TeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") TeacherMark record, @Param("example") TeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(TeacherMark record);
}