package com.erircs.pojos;

import java.util.Date;

public class Classroom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.class_name
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.create_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.class_id
     *
     * @return the value of classroom.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.class_id
     *
     * @param classId the value for classroom.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.teacher_id
     *
     * @return the value of classroom.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.teacher_id
     *
     * @param teacherId the value for classroom.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.class_name
     *
     * @return the value of classroom.class_name
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.class_name
     *
     * @param className the value for classroom.class_name
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.create_time
     *
     * @return the value of classroom.create_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.create_time
     *
     * @param createTime the value for classroom.create_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}