package com.erircs.pojos;

import java.util.Date;

public class ClassModel extends ClassModelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_model.create_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_model.create_time
     *
     * @return the value of class_model.create_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_model.create_time
     *
     * @param createTime the value for class_model.create_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}