package com.erircs.pojos;

public class ClassDocument {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_document.document_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_document.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_document.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_document.document_id
     *
     * @return the value of class_document.document_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_document.document_id
     *
     * @param documentId the value for class_document.document_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_document.class_id
     *
     * @return the value of class_document.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_document.class_id
     *
     * @param classId the value for class_document.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_document.file_path
     *
     * @return the value of class_document.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_document.file_path
     *
     * @param filePath the value for class_document.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
}