package com.erircs.pojos;

import java.util.Date;

public class StudentSubmit extends StudentSubmitKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_submit.submit_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Date submitTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_submit.submit_time
     *
     * @return the value of student_submit.submit_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_submit.submit_time
     *
     * @param submitTime the value for student_submit.submit_time
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }
}