package com.erircs.pojos;

public class StudentMark extends StudentMarkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_mark.student_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer studentScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_mark.annotation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String annotation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_mark.explanation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String explanation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_mark.student_score
     *
     * @return the value of student_mark.student_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getStudentScore() {
        return studentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_mark.student_score
     *
     * @param studentScore the value for student_mark.student_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setStudentScore(Integer studentScore) {
        this.studentScore = studentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_mark.annotation
     *
     * @return the value of student_mark.annotation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getAnnotation() {
        return annotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_mark.annotation
     *
     * @param annotation the value for student_mark.annotation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_mark.explanation
     *
     * @return the value of student_mark.explanation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getExplanation() {
        return explanation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_mark.explanation
     *
     * @param explanation the value for student_mark.explanation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }
}