package com.erircs.pojos;

public class SubmitAnswer extends SubmitAnswerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_answer.answer_content
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String answerContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_answer.answer_content
     *
     * @return the value of submit_answer.answer_content
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_answer.answer_content
     *
     * @param answerContent the value for submit_answer.answer_content
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent;
    }
}