package com.erircs.pojos;

public class SubmitAnswerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_answer.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_answer.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer submitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_answer.question_id
     *
     * @return the value of submit_answer.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_answer.question_id
     *
     * @param questionId the value for submit_answer.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_answer.submit_id
     *
     * @return the value of submit_answer.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getSubmitId() {
        return submitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_answer.submit_id
     *
     * @param submitId the value for submit_answer.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setSubmitId(Integer submitId) {
        this.submitId = submitId;
    }
}