package com.erircs.pojos;

public class TeacherMark extends TeacherMarkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_mark.teacher_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer teacherScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_mark.annotation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String annotation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_mark.explanation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String explanation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_mark.teacher_score
     *
     * @return the value of teacher_mark.teacher_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getTeacherScore() {
        return teacherScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_mark.teacher_score
     *
     * @param teacherScore the value for teacher_mark.teacher_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setTeacherScore(Integer teacherScore) {
        this.teacherScore = teacherScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_mark.annotation
     *
     * @return the value of teacher_mark.annotation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getAnnotation() {
        return annotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_mark.annotation
     *
     * @param annotation the value for teacher_mark.annotation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_mark.explanation
     *
     * @return the value of teacher_mark.explanation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getExplanation() {
        return explanation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_mark.explanation
     *
     * @param explanation the value for teacher_mark.explanation
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }
}