package org.erircs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.erircs.pojos.ClassModel;
import org.erircs.pojos.ClassModelExample;
import org.erircs.pojos.ClassModelKey;

public interface ClassModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(ClassModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(ClassModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(ClassModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(ClassModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(ClassModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<ClassModel> selectByExample(ClassModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    ClassModel selectByPrimaryKey(ClassModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ClassModel record, @Param("example") ClassModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") ClassModel record, @Param("example") ClassModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(ClassModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(ClassModel record);
}