package org.erircs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.erircs.pojos.ClassDocument;
import org.erircs.pojos.ClassDocumentExample;

public interface ClassDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(ClassDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(ClassDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(Integer documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(ClassDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(ClassDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<ClassDocument> selectByExample(ClassDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    ClassDocument selectByPrimaryKey(Integer documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ClassDocument record, @Param("example") ClassDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") ClassDocument record, @Param("example") ClassDocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(ClassDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_document
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(ClassDocument record);
}