package org.erircs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.erircs.pojos.ReportModel;
import org.erircs.pojos.ReportModelExample;

public interface ReportModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(ReportModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(ReportModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(ReportModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(ReportModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<ReportModel> selectByExample(ReportModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    ReportModel selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ReportModel record, @Param("example") ReportModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") ReportModel record, @Param("example") ReportModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(ReportModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_model
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(ReportModel record);
}