package org.erircs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.erircs.pojos.ReportSubmit;
import org.erircs.pojos.ReportSubmitExample;

public interface ReportSubmitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(ReportSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(ReportSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(Integer submitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(ReportSubmit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(ReportSubmit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<ReportSubmit> selectByExample(ReportSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    ReportSubmit selectByPrimaryKey(Integer submitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ReportSubmit record, @Param("example") ReportSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") ReportSubmit record, @Param("example") ReportSubmitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(ReportSubmit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_submit
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(ReportSubmit record);
}