package org.erircs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.erircs.pojos.ReportAnswer;
import org.erircs.pojos.ReportAnswerExample;

public interface ReportAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(ReportAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(ReportAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(ReportAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(ReportAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<ReportAnswer> selectByExample(ReportAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    ReportAnswer selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ReportAnswer record, @Param("example") ReportAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") ReportAnswer record, @Param("example") ReportAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(ReportAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_answer
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(ReportAnswer record);
}