package org.erircs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.erircs.pojos.StudentMark;
import org.erircs.pojos.StudentMarkExample;
import org.erircs.pojos.StudentMarkKey;

public interface StudentMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    long countByExample(StudentMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByExample(StudentMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(StudentMarkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insert(StudentMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int insertSelective(StudentMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    List<StudentMark> selectByExample(StudentMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    StudentMark selectByPrimaryKey(StudentMarkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") StudentMark record, @Param("example") StudentMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") StudentMark record, @Param("example") StudentMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(StudentMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_mark
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    int updateByPrimaryKey(StudentMark record);
}