package org.erircs.pojos;

public class ClassModelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_model.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_model.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer classId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_model.model_id
     *
     * @return the value of class_model.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_model.model_id
     *
     * @param modelId the value for class_model.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_model.class_id
     *
     * @return the value of class_model.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_model.class_id
     *
     * @param classId the value for class_model.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
}