package org.erircs.pojos;

public class ReportModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_model.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_model.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_model.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_model.model_id
     *
     * @return the value of report_model.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_model.model_id
     *
     * @param modelId the value for report_model.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_model.teacher_id
     *
     * @return the value of report_model.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_model.teacher_id
     *
     * @param teacherId the value for report_model.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_model.file_path
     *
     * @return the value of report_model.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_model.file_path
     *
     * @param filePath the value for report_model.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
}