package org.erircs.pojos;

public class ReportQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_question.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_question.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_question.question_head
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String questionHead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_question.question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_question.max_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer maxScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_question.question_id
     *
     * @return the value of report_question.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_question.question_id
     *
     * @param questionId the value for report_question.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_question.model_id
     *
     * @return the value of report_question.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_question.model_id
     *
     * @param modelId the value for report_question.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_question.question_head
     *
     * @return the value of report_question.question_head
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getQuestionHead() {
        return questionHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_question.question_head
     *
     * @param questionHead the value for report_question.question_head
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setQuestionHead(String questionHead) {
        this.questionHead = questionHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_question.question
     *
     * @return the value of report_question.question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_question.question
     *
     * @param question the value for report_question.question
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_question.max_score
     *
     * @return the value of report_question.max_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_question.max_score
     *
     * @param maxScore the value for report_question.max_score
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }
}