package org.erircs.pojos;

public class ReportAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_answer.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_answer.answer_content
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String answerContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_answer.question_id
     *
     * @return the value of report_answer.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_answer.question_id
     *
     * @param questionId the value for report_answer.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_answer.answer_content
     *
     * @return the value of report_answer.answer_content
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_answer.answer_content
     *
     * @param answerContent the value for report_answer.answer_content
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent;
    }
}