package org.erircs.pojos;

public class ReportSubmit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_submit.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer submitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_submit.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_submit.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_submit.submit_id
     *
     * @return the value of report_submit.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getSubmitId() {
        return submitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_submit.submit_id
     *
     * @param submitId the value for report_submit.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setSubmitId(Integer submitId) {
        this.submitId = submitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_submit.model_id
     *
     * @return the value of report_submit.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_submit.model_id
     *
     * @param modelId the value for report_submit.model_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_submit.file_path
     *
     * @return the value of report_submit.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_submit.file_path
     *
     * @param filePath the value for report_submit.file_path
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
}