package org.erircs.pojos;

public class StudentClassKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_class.student_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_class.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer classId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_class.student_id
     *
     * @return the value of student_class.student_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_class.student_id
     *
     * @param studentId the value for student_class.student_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_class.class_id
     *
     * @return the value of student_class.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_class.class_id
     *
     * @param classId the value for student_class.class_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
}