package org.erircs.pojos;

public class TeacherMarkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_mark.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_mark.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private Integer submitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_mark.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    private String teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_mark.question_id
     *
     * @return the value of teacher_mark.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_mark.question_id
     *
     * @param questionId the value for teacher_mark.question_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_mark.submit_id
     *
     * @return the value of teacher_mark.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public Integer getSubmitId() {
        return submitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_mark.submit_id
     *
     * @param submitId the value for teacher_mark.submit_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setSubmitId(Integer submitId) {
        this.submitId = submitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_mark.teacher_id
     *
     * @return the value of teacher_mark.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_mark.teacher_id
     *
     * @param teacherId the value for teacher_mark.teacher_id
     *
     * @mbg.generated Sun Jul 22 15:12:54 CST 2018
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
}